### ISSUE TITLE
Error while loading in new .ics File!

### ISSUE THREAD

**Issue by phibr0** [TesteurManiak/icalendar_parser#2]
Many auto generated .ics Files end with an empty line under the `END:VCALENDAR`, but this package throws an error saying the file doesnt end with an `END:VCALENDAR` Statement. If i find some time in the near future i will propably open a Pull Request fixing this issue.

**Comment by TesteurManiak** [comment]
You are right, I'm going to fix this but if you open a PR I'll be glad to merge it :)

**Comment by TesteurManiak** [comment]
Just've made a fix published in version `0.1.1` of the package. If empty lines are allowed in the parsing (which is enabled by default) it won't throw an error anymore if there is a newline at the end of the file.
