### ISSUE TITLE
Date is not correctly parsed

### ISSUE THREAD

**Issue by dg76** [TesteurManiak/icalendar_parser#27]
Hi!

DTSTART;TZID=Europe/Berlin:20210607T090000

is being parsed as

DateTime:<2021-10-31 01:00:00.000Z>

As you can see the date and time is incorrectly parsed. :-( I think using "DateTime.parse(text)" is not enough.

**Comment by TesteurManiak** [comment]
Hi, I'm going to look into it to see if I can parse it better, last resort solution would be to save it as a `String` instead of trying to parse it.

**Comment by TesteurManiak** [comment]
So it is not really a bug, the issue is that I do not supports parameters when parsing, and the `DateTime` object does not support the timezone, parsing with the timezone might be possible by using the package https://pub.dev/packages/timezone but it implies to rewrite the implementation, for now I might create a custom object to save the timezone and the non-parsed datetime as a `String`.
Would that work for you ?.

**Comment by dg76** [comment]
Actually I just wanted to tell you about the problem so that you could maybe fix that in the future if you like. I just needed it for a test case to verify an ICS file. But I have found another solution for me now: I have already parsed ICS files in Java and Objective C so I could just reuse some of the code and build a simple ICS parser in Flutter myself now that is sufficient for my test case. It is very simple and supports only strings but for my tests it is sufficient.

So for me you don't need to change it, I just wanted to mention it so that you know that this problem exists. :-) Thank you very much for your very quick replies! 👍

**Comment by TesteurManiak** [comment]
From https://github.com/TesteurManiak/icalendar_parser/pull/28#issue-661771168
> 
> As `DateTime` doesn't support timezones I cannot provide a full parsing for ics datetime object. Still I've created an `IcsDateTime` object to keep all the data so you can easily finish the parsing by yourself using the [timezone](https://pub.dev/packages/timezone) package:
> 
> ## Timezone example
> ```dart
> import 'package:timezone/standalone.dart' as tz;
> 
> final icsDt = IcsDateTime(/* ... */);
> final date = tz.TZDateTime.parse(tz.getLocation(icsDt.tzid), icsDt.dt);
> ```
> 
> ## `IcsDateTime` implementation
> ```dart
> class IcsDateTime {
>   final String? tzid;
>   final String dt;
> 
>   IcsDateTime({this.tzid, required this.dt});
> 
>   DateTime? toDateTime() => DateTime.tryParse(dt);
> 
>   Map<String, dynamic> toJson() {
>     final json = <String, dynamic>{'dt': dt};
>     if (tzid != null) json['tzid'] = tzid;
>     return json;
>   }
> }
> ```

**Comment by dg76** [comment]
Thank you, that seems to be a good solution! :-)
