### ISSUE TITLE
Add built-in support for `CREATED` property

### ISSUE THREAD

**Issue by emme1444** [TesteurManiak/icalendar_parser#46]
If I understand correctly, according to the spec [here](https://icalendar.org/iCalendar-RFC-5545/3-8-7-1-date-time-created.html), the `CREATED` property is built-in (to the spec?). Or it's just not a common (and optional) property, enough to include in this package.

Any chance this can be built in to `icalendar_parser`? If so, I could take a stab at a PR maybe. Are there any related tests stuff that I would need to implement, if so what?

Thanks!

Full link to spec: https://icalendar.org/iCalendar-RFC-5545/3-8-7-1-date-time-created.html

**Comment by TesteurManiak** [comment]
If you need it right now in a project you can already implement the parsing logic with the `ICalendar.registerField` method.

I have no objection to add this property directly into the package, the object type would be an `IcsDateTime` to support timezones.

A dedicated unit test would be much appreciated to ensure that the parsing works well, it would require to create a dedicated ics test file with the `CREATED` property (example value taken from the doc: `CREATED:19960329T133000Z`)
